export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    switchCompany: '/auth/switch-company',
  },
  products: '/products',
  posProducts: '/pos/products',
  categories: '/categories',
  inventory: {
    stock: '/inventory/stock',
    batches: '/inventory/batches',
    movements: '/inventory/movements',
    receive: '/inventory/receive',
    adjust: '/inventory/adjust',
    transfers: '/inventory/transfers',
    transferHistory: '/inventory/transfers',
  },
  branches: '/branches',
  warehouses: '/warehouses',
  warehouseById: (id: string) => `/warehouses/${id}`,
  warehouseDashboard: (id: string) => `/warehouses/${id}/dashboard`,
  warehouseReports: (id: string) => `/warehouses/${id}/reports`,
  warehouseDeactivate: (id: string) => `/warehouses/${id}/deactivate`,
  sales: '/sales',
  salesReturns: '/sales/returns',
  customers: '/customers',
  suppliers: '/suppliers',
  debtPayments: '/debt-payments',
  debt: {
    summary: '/debt/summary',
    customers: '/debt/customers',
    aging: '/debt/aging',
  },
  currency: {
    rate: '/currency/rate',
    rates: '/currency/rates',
    convert: '/currency/convert',
  },
  health: '/health',
  admin: {
    overview: '/admin/overview',
    monitoring: '/admin/monitoring',
    health: '/admin/monitoring/health',
    queue: '/admin/monitoring/queue',
    logs: '/admin/logs',
    backups: '/admin/backups',
    backupSchedule: '/admin/backups/schedule',
    backupById: (id: string) => `/admin/backups/${id}`,
    backupDownload: (id: string) => `/admin/backups/${id}/download`,
    backupRestore: (id: string) => `/admin/backups/${id}/restore`,
    users: '/admin/users',
    sessions: '/admin/sessions',
    devices: '/admin/devices',
    auditLogs: '/admin/audit-logs',
    roles: '/admin/roles',
    permissions: '/admin/permissions',
  },
  analytics: {
    overview: '/analytics/overview',
    metrics: '/analytics/metrics',
    dashboardKpi: '/analytics/dashboard/kpi',
    sales: '/analytics/sales',
    revenue: '/analytics/revenue',
    profit: '/analytics/profit',
    suppliers: '/analytics/suppliers',
    customers: '/analytics/customers',
    products: '/analytics/products',
    topProducts: '/analytics/top/products',
    topCustomers: '/analytics/top/customers',
    topSuppliers: '/analytics/top/suppliers',
    revenueProfitChart: '/analytics/charts/revenue-profit',
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markAllRead: '/notifications/mark-all-read',
    scanAlerts: '/notifications/scan-alerts',
    byId: (id: string) => `/notifications/${id}`,
    read: (id: string) => `/notifications/${id}/read`,
    unread: (id: string) => `/notifications/${id}/unread`,
  },
} as const;
