import { ReportCatalogEntry } from './report.types';

export const REPORT_CATALOG: ReportCatalogEntry[] = [
  // Sales
  {
    id: 'sales_daily_summary',
    template: 'daily_summary',
    category: 'Savdo',
    categoryCode: 'sales',
    name: 'Kunlik savdo hisoboti',
    description: "Kunlik savdo, to'lov va qarz ko'rsatkichlari",
    permission: 'reports.sales',
  },
  {
    id: 'sales_detail',
    template: 'detail',
    category: 'Savdo',
    categoryCode: 'sales',
    name: 'Savdo tafsilotlari',
    description: 'Davr bo\'yicha barcha savdolar',
    permission: 'reports.sales',
  },
  {
    id: 'sales_by_product',
    template: 'by_product',
    category: 'Savdo',
    categoryCode: 'sales',
    name: 'Mahsulot bo\'yicha savdo',
    description: 'Mahsulotlar bo\'yicha daromad va foyda',
    permission: 'reports.sales',
  },
  {
    id: 'sales_by_category',
    template: 'by_category',
    category: 'Savdo',
    categoryCode: 'sales',
    name: 'Kategoriya bo\'yicha savdo',
    description: 'Kategoriyalar bo\'yicha daromad',
    permission: 'reports.sales',
  },
  {
    id: 'sales_by_cashier',
    template: 'by_cashier',
    category: 'Savdo',
    categoryCode: 'sales',
    name: 'Kassir faoliyati',
    description: 'Kassirlar bo\'yicha savdo statistikasi',
    permission: 'reports.sales',
  },
  {
    id: 'sales_by_branch',
    template: 'by_branch',
    category: 'Savdo',
    categoryCode: 'sales',
    name: 'Filial bo\'yicha savdo',
    description: 'Filiallar bo\'yicha daromad',
    permission: 'reports.sales',
  },
  {
    id: 'sales_returns',
    template: 'returns',
    category: 'Savdo',
    categoryCode: 'sales',
    name: 'Qaytarishlar hisoboti',
    description: 'Davr bo\'yicha qaytarishlar',
    permission: 'reports.sales',
  },
  // Products
  {
    id: 'products_turnover',
    template: 'turnover',
    category: 'Mahsulotlar',
    categoryCode: 'products',
    name: 'Mahsulot aylanmasi',
    description: 'Eng ko\'p va kam sotiladigan mahsulotlar',
    permission: 'reports.sales',
  },
  {
    id: 'products_top_selling',
    template: 'top_selling',
    category: 'Mahsulotlar',
    categoryCode: 'products',
    name: 'Eng ko\'p sotilgan',
    description: 'Top mahsulotlar reytingi',
    permission: 'reports.sales',
  },
  {
    id: 'products_slow_moving',
    template: 'slow_moving',
    category: 'Mahsulotlar',
    categoryCode: 'products',
    name: 'Sekin aylanuvchi mahsulotlar',
    description: 'Kam sotiladigan mahsulotlar',
    permission: 'reports.sales',
  },
  // Inventory
  {
    id: 'inventory_stock_level',
    template: 'stock_level',
    category: 'Ombor',
    categoryCode: 'inventory',
    name: 'Ombor qoldig\'i',
    description: 'Mahsulotlar bo\'yicha qoldiq va qiymat',
    permission: 'reports.inventory',
  },
  {
    id: 'inventory_valuation',
    template: 'valuation',
    category: 'Ombor',
    categoryCode: 'inventory',
    name: 'Ombor qiymati',
    description: 'Kategoriyalar bo\'yicha ombor qiymati',
    permission: 'reports.inventory',
  },
  {
    id: 'inventory_low_stock',
    template: 'low_stock',
    category: 'Ombor',
    categoryCode: 'inventory',
    name: 'Kam qoldiq',
    description: 'Minimal darajadan past mahsulotlar',
    permission: 'reports.inventory',
  },
  {
    id: 'inventory_movements',
    template: 'movements',
    category: 'Ombor',
    categoryCode: 'inventory',
    name: 'Harakatlar tarixi',
    description: 'Ombor harakatlari',
    permission: 'reports.inventory',
  },
  {
    id: 'inventory_batches',
    template: 'batches',
    category: 'Ombor',
    categoryCode: 'inventory',
    name: 'Partiyalar hisoboti',
    description: 'Faol partiyalar tafsiloti',
    permission: 'reports.inventory',
  },
  // Customers
  {
    id: 'customers_summary',
    template: 'summary',
    category: 'Mijozlar',
    categoryCode: 'customers',
    name: 'Mijozlar xulosasi',
    description: 'Mijozlar statistikasi',
    permission: 'reports.view',
  },
  {
    id: 'customers_top_buyers',
    template: 'top_buyers',
    category: 'Mijozlar',
    categoryCode: 'customers',
    name: 'Eng yaxshi mijozlar',
    description: 'Eng ko\'p xarid qilgan mijozlar',
    permission: 'reports.view',
  },
  // Suppliers
  {
    id: 'suppliers_summary',
    template: 'summary',
    category: 'Yetkazib beruvchilar',
    categoryCode: 'suppliers',
    name: 'Yetkazib beruvchilar xulosasi',
    description: 'Yetkazib beruvchilar statistikasi',
    permission: 'reports.view',
  },
  {
    id: 'suppliers_debt',
    template: 'debt_list',
    category: 'Yetkazib beruvchilar',
    categoryCode: 'suppliers',
    name: 'Yetkazib beruvchi qarzlari',
    description: 'Qarzdor yetkazib beruvchilar',
    permission: 'reports.view',
  },
  // Debt
  {
    id: 'debt_summary',
    template: 'summary',
    category: 'Qarz',
    categoryCode: 'debt',
    name: 'Mijozlar qarzi',
    description: 'Qarzdor mijozlar va muddat o\'tgan to\'lovlar',
    permission: 'reports.debt',
  },
  {
    id: 'debt_aging',
    template: 'aging',
    category: 'Qarz',
    categoryCode: 'debt',
    name: 'Qarz yoshlanishi',
    description: 'Qarz yoshlanish tahlili',
    permission: 'reports.debt',
  },
  {
    id: 'debt_payments',
    template: 'payments',
    category: 'Qarz',
    categoryCode: 'debt',
    name: 'To\'lovlar tarixi',
    description: 'Davr bo\'yicha qarz to\'lovlari',
    permission: 'reports.debt',
  },
  {
    id: 'debt_top_debtors',
    template: 'top_debtors',
    category: 'Qarz',
    categoryCode: 'debt',
    name: 'Eng katta qarzdorlar',
    description: 'Eng yuqori qarz balanslari',
    permission: 'reports.debt',
  },
  // Expenses
  {
    id: 'expenses_by_category',
    template: 'by_category',
    category: 'Xarajatlar',
    categoryCode: 'expenses',
    name: 'Xarajatlar kategoriyasi',
    description: 'Kategoriyalar bo\'yicha xarajatlar',
    permission: 'reports.financial',
  },
  {
    id: 'expenses_detail',
    template: 'detail',
    category: 'Xarajatlar',
    categoryCode: 'expenses',
    name: 'Xarajatlar tafsiloti',
    description: 'Barcha xarajatlar ro\'yxati',
    permission: 'reports.financial',
  },
  {
    id: 'expenses_monthly_trend',
    template: 'monthly_trend',
    category: 'Xarajatlar',
    categoryCode: 'expenses',
    name: 'Oylik xarajat trendi',
    description: 'Oylar bo\'yicha xarajat dinamikasi',
    permission: 'reports.financial',
  },
  // Profit
  {
    id: 'profit_gross',
    template: 'gross_profit',
    category: 'Moliya',
    categoryCode: 'profit',
    name: 'Oylik foyda va zarar',
    description: 'Daromad, xarajat va yalpi foyda tahlili',
    permission: 'reports.financial',
  },
  {
    id: 'profit_by_product',
    template: 'by_product',
    category: 'Moliya',
    categoryCode: 'profit',
    name: 'Mahsulot bo\'yicha foyda',
    description: 'Mahsulotlar rentabelligi',
    permission: 'reports.financial',
  },
  {
    id: 'profit_by_category',
    template: 'by_category',
    category: 'Moliya',
    categoryCode: 'profit',
    name: 'Kategoriya bo\'yicha foyda',
    description: 'Kategoriyalar rentabelligi',
    permission: 'reports.financial',
  },
  {
    id: 'profit_cogs',
    template: 'cogs_detail',
    category: 'Moliya',
    categoryCode: 'profit',
    name: 'COGS tafsiloti',
    description: 'FIFO bo\'yicha tannarx taqsimoti',
    permission: 'reports.financial',
  },
];

export function findCatalogEntry(categoryCode: string, template: string): ReportCatalogEntry | undefined {
  return REPORT_CATALOG.find((e) => e.categoryCode === categoryCode && e.template === template);
}

export function findCatalogEntryById(id: string): ReportCatalogEntry | undefined {
  return REPORT_CATALOG.find((e) => e.id === id);
}

export const CATEGORY_PERMISSION_MAP: Record<string, string> = {
  sales: 'reports.sales',
  products: 'reports.sales',
  inventory: 'reports.inventory',
  customers: 'reports.view',
  suppliers: 'reports.view',
  debt: 'reports.debt',
  expenses: 'reports.financial',
  profit: 'reports.financial',
};
